#!/usr/bin/env python

# This code was generated by ros-pubsub-gen
# https://github.com/tilt-silvie/ros-pubsub-gen
#
# DO NOT modify this file.

import rospy
from std_msgs.msg import Int32
from std_msgs.msg import String

# publishers
# pub_0: This is description of pub_0
pub_0 = rospy.Publisher('/pub_0', String, queue_size=10)
# pub_1: This is description of pub_1
pub_1 = rospy.Publisher('pub_1', Int32, queue_size=10)

# subscribers (definition only. Instantiation is in init().)
# sub_0: This is description of sub_0
sub_0 = None
# sub_1: This is description of sub_1
sub_1 = None


def init(callbacks):
    global sub_0, sub_1
    sub_0 = rospy.Subscriber('sub_0', String, callbacks['sub_0'])
    sub_1 = rospy.Subscriber('sub_1', Int32, callbacks['sub_1'])
